name: demo

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  echo_demo:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest]
    steps:
      - name: Print
        run: echo hello demo
      - name: Print 2
        run: echo hello demo 2
    
