name: demo

on:
  push:
    branches:
      - main
jobs:
  echo_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print
        run: echo hello demo
      - name: Print 2
        run: echo hello demo 2
    
